--CREATE TABLE COMMSTND (
--STNDETGB VARCHAR2(3),
--STNDETCD VARCHAR2(8),
--STNDSYNM VARCHAR2(10),
--STNDFUNM VARCHAR2(30),
--STNDSHNM VARCHAR2(20),
--STNDRKDS VARCHAR2(70),
--PRIMARY KEY(STNDETGB,STNDETCD ))

SELECT * FROM COMMSTND

DROP VIEW COD_CNTR_SIZE

CREATE OR REPLACE VIEW COD_CNTR_SIZE
AS SELECT STNDETCD AS "CODE",
          STNDFUNM AS "DESC"  
     FROM COMMSTND
   WHERE STNDETGB = '803'
     AND STNDSYNM = 'GO'
     
     
     SELECT * FROM COD_CNTR_SIZE