--CREATE TABLE COMMSTND (
--STNDETGB VARCHAR2(3),
--STNDETCD VARCHAR2(8),
--STNDSYNM VARCHAR2(10),
--STNDFUNM VARCHAR2(30),
--STNDSHNM VARCHAR2(20),
--STNDRKDS VARCHAR2(70),
--PRIMARY KEY(STNDETGB,STNDETCD ))

SELECT * FROM COMMSTND FETCH First ROW ONLY
  

DROP VIEW COD_CNTR_SIZE

CREATE OR REPLACE VIEW COD_CNTR_SIZE
AS SELECT STNDETCD AS "CODE",
          STNDFUNM AS "DESC"  
     FROM COMMSTND
   WHERE STNDETGB = '803'
     AND STNDSYNM = 'GO'
     
     
     SELECT * FROM COD_CNTR_SIZE
     
     
     DROP VIEW COD_CNTR_TYPE
     
     CREATE OR REPLACE VIEW COD_CNTR_TYPE
AS SELECT SUBSTR(STNDETCD,1,3) AS "CODE",
          STNDSHNM AS "TYPE",
          STNDFUNM AS "DESC"  
     FROM COMMSTND
   WHERE STNDETGB = '813'
     AND STNDSYNM = 'GO'
     
     
     SELECT * FROM COD_CNTR_TYPE
     
     