--CREATE TABLE COMMSTND (
--STNDETGB VARCHAR2(3),
--STNDETCD VARCHAR2(8),
--STNDSYNM VARCHAR2(10),
--STNDFUNM VARCHAR2(30),
--STNDSHNM VARCHAR2(20),
--STNDRKDS VARCHAR2(70),
--PRIMARY KEY(STNDETGB,STNDETCD ))

--SELECT * FROM COMMSTND FETCH First ROW ONLY
--  
--
--DROP VIEW COD_CNTR_SIZE
--
--v
--AS SELECT STNDETCD AS "CODE",
--          STNDFUNM AS "DESC"  
--     FROM COMMSTND
--   WHERE STNDETGB = '803'
--     AND STNDSYNM = 'GO'
--     
--     
--     SELECT * FROM COD_CNTR_SIZE
--     
--     
--     DROP VIEW COD_CNTR_TYPE
--     
--     CREATE OR REPLACE VIEW COD_CNTR_TYPE
--AS SELECT SUBSTR(STNDETCD,1,3) AS "CODE",
--          STNDSHNM AS "TYPE",
--          STNDFUNM AS "DESC"  
--     FROM COMMSTND
--   WHERE STNDETGB = '813'
--     AND STNDSYNM = 'GO'
--     
--     
--     SELECT * FROM COD_CNTR_TYPE
     
--CREATE TABLE IF_BK_CNT (
--	IFB_OPER VARCHAR2(3),
--	IFB_BKNO VARCHAR2(20),
--	IFB_ISO VARCHAR2(4),
--	IFB_SIZE VARCHAR2(2),
--	IFB_TYPE VARCHAR2(2),
--	IFB_CNT NUMBER(3,0),
--	IFB_DATE DATE,
--	IFB_SENDER VARCHAR2(9),
--	IFB_RECEIVER VARCHAR2(9),
--	IFB_SEND_YN VARCHAR2(1),
--	IFB_SEND_DT DATE
--);


SELECT * FROM yj.if_bk_cnt

CREATE OR REPLACE VIEW COD_CNTR_TYPE



